"""lob_run20260420_iter2_obi1_maker_fixed — auto-generated by strategy-coder.

LOB spread_capture strategy using OBI depth=1 signal (passive maker).
This is iter-2 with 4 critical bug-fixes over iter-1:

  Fix 1 — OBI gate BEFORE LIMIT post: obi_1 >= sym_thresh is the LAST
           check immediately before Order() construction — no code path
           can bypass it and reach submit_limit_buy.

  Fix 2 — Pre-order position cap: pos_qty > 0 OR sym in _pending_buy
           evaluated as the FIRST check in the entry block (even though
           the latency guard above already blocks _pending_buy, this
           explicit second check prevents any future refactor from
           inadvertently opening a bypass path).

  Fix 3 — TTL=30 ticks (not 10), cancel_on_bid_drop=3 ticks (not 1):
           wider tolerances recover fill rate without relaxing alpha.

  Fix 4 — time_stop_ticks is an independent param (default 10) distinct
           from entry_ttl_ticks — iter-1 reused entry_ttl_ticks for both
           roles which was confusing and wrong when TTL changed.

Entry:  LIMIT BUY at bid_px[0] (passive maker, 0 bps fee) when
        (1) not holding and not pending,
        (2) session entries < max_entries_per_session,
        (3) spread_bps < profit_target_bps (spread gate),
        (4) obi_1 >= obi_thresholds[sym]  ← checked last, mandatory.
Exit priority (all via MARKET SELL):
        (1) profit_target_bps (1.21 bps),
        (2) stop_loss_bps (1.64 bps, bid_px[0]-based, 5-tick guard),
        (3) time_stop_ticks (10 ticks post-fill).
Cancel: TTL (30 ticks) and bid-drop (3 ticks × tick_size).

Patterns from python_impl_patterns.md:
  sl_on_bid_px, per_symbol_spread_gate, latency_guard, entry_ttl,
  bid_drop_cancel, max_entries_per_session, tick_size_estimation
"""
from __future__ import annotations

from collections import deque
from datetime import datetime, timezone

from engine.data_loader import OrderBookSnapshot
from engine.signals import SIGNAL_REGISTRY, SymbolState, update_state
from engine.simulator import BUY, CANCEL, LIMIT, MARKET, SELL, Context, Order

# ---------------------------------------------------------------------------
# Module-level constant
# ---------------------------------------------------------------------------
_MAX_PENDING_TICKS = 100  # staleness timeout — assume rejected after N ticks


class Strategy:
    def __init__(self, spec: dict) -> None:
        p = spec.get("params") or {}

        # --- alpha params ---
        raw_thresholds = p.get("obi_thresholds", {})
        self.obi_thresholds: dict[str, float] = {k: float(v) for k, v in raw_thresholds.items()}
        self.spread_gate: bool = bool(p.get("spread_gate", True))

        # --- entry execution params (iter-2 fixed values) ---
        self.entry_ttl_ticks: int = int(p.get("entry_ttl_ticks", 30))          # Fix 3: 10→30
        self.cancel_on_bid_drop_ticks: int = int(p.get("cancel_on_bid_drop_ticks", 3))  # Fix 3: 1→3

        # --- exit execution params ---
        self.profit_target_bps: float = float(p.get("profit_target_bps", 1.21))
        self.stop_loss_bps: float = float(p.get("stop_loss_bps", 1.64))
        # Fix 4: separate time_stop_ticks param — NOT reusing entry_ttl_ticks
        self.time_stop_ticks: int = int(p.get("time_stop_ticks", 10))
        self.trailing_stop: bool = bool(p.get("trailing_stop", False))

        # --- sizing / session ---
        self.lot_size: int = int(p.get("lot_size", 1))
        self.max_entries_per_session: int = int(p.get("max_entries_per_session", 5))
        self.max_position_per_symbol: int = int(p.get("max_position_per_symbol", 1))

        # --- signal states (engine signals) ---
        self.states: dict[str, SymbolState] = {}

        # --- per-symbol tick counter (global, not reset per day) ---
        self._tick_count: dict[str, int] = {}

        # --- latency guard: pending buy/sell ---
        # Value = tick number when order was submitted (for staleness timeout).
        self._pending_buy: dict[str, int] = {}
        self._pending_sell: dict[str, int] = {}

        # --- TTL and bid-drop cancel ---
        # _submit_tick and _pending_buy are always set/cleared together.
        self._submit_tick: dict[str, int] = {}   # sym → tc at BUY LIMIT submit
        self._submit_bid: dict[str, int] = {}    # sym → bid_px[0] at BUY LIMIT submit

        # --- ticks held in position (for time_stop + 5-tick SL guard) ---
        self._ticks_held: dict[str, int] = {}

        # --- session entry counter ---
        self._entries_today: dict[str, int] = {}
        self._last_date: dict[str, str] = {}

        # --- bid buffer for tick size estimation (§10 python_impl_patterns) ---
        self._bid_buf: dict[str, deque] = {}

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _sym_state(self, symbol: str) -> SymbolState:
        if symbol not in self.states:
            self.states[symbol] = SymbolState(symbol=symbol)
        return self.states[symbol]

    def _update_bid_buf(self, snap: OrderBookSnapshot) -> None:
        sym = snap.symbol
        buf = self._bid_buf.setdefault(sym, deque(maxlen=20))
        buf.append(int(snap.bid_px[0]))

    def _tick_size(self, sym: str, fallback: int = 1) -> int:
        """Estimate tick size from recent bid_px[0] diffs (§10 python_impl_patterns)."""
        buf = self._bid_buf.get(sym)
        if not buf or len(buf) < 2:
            return fallback
        diffs = [abs(buf[i] - buf[i - 1]) for i in range(1, len(buf))]
        nonzero = [d for d in diffs if d > 0]
        return min(nonzero) if nonzero else fallback

    def _spread_bps(self, snap: OrderBookSnapshot) -> float:
        """spread_bps — manual calculation (no property on OrderBookSnapshot, §3)."""
        mid = float(snap.mid)
        if mid <= 0:
            return 0.0
        return float(snap.spread) / mid * 1e4

    def _date_reset(self, snap: OrderBookSnapshot) -> None:
        """Reset per-session counter when UTC date changes (§4 python_impl_patterns)."""
        sym = snap.symbol
        dt = datetime.fromtimestamp(snap.ts_ns / 1e9, tz=timezone.utc)
        date_str = dt.strftime("%Y%m%d")
        if self._last_date.get(sym) != date_str:
            self._last_date[sym] = date_str
            self._entries_today[sym] = 0

    def _clear_pending_buy(self, sym: str) -> None:
        """Remove all buy-submission tracking for a symbol atomically."""
        self._pending_buy.pop(sym, None)
        self._submit_tick.pop(sym, None)
        self._submit_bid.pop(sym, None)

    # ------------------------------------------------------------------
    # Main tick handler
    # ------------------------------------------------------------------

    def on_tick(self, snap: OrderBookSnapshot, ctx: Context) -> list[Order]:
        sym = snap.symbol

        # 1. Increment per-symbol tick counter
        tc = self._tick_count.get(sym, 0) + 1
        self._tick_count[sym] = tc

        # 2. Update signal state + bid buffer
        st = self._sym_state(sym)
        update_state(st, snap)
        self._update_bid_buf(snap)

        # 3. Date-change reset (session counter) — UTC basis, never datetime.now()
        self._date_reset(snap)

        # 4. Current position (read-only)
        pos = ctx.portfolio.positions.get(sym)
        pos_qty = pos.qty if pos else 0

        # ------------------------------------------------------------------
        # 5. Fill confirmation — check if pending buy/sell has resolved
        # ------------------------------------------------------------------

        # BUY fill confirmation: pos_qty went from 0 → >0
        if sym in self._pending_buy:
            if pos_qty > 0:
                # Fill confirmed — initialise exit tracking; clear submission state
                self._pending_buy.pop(sym)
                self._submit_tick.pop(sym, None)
                self._submit_bid.pop(sym, None)
                self._ticks_held[sym] = 0
            elif tc - self._pending_buy[sym] >= _MAX_PENDING_TICKS:
                # Assumed rejected / expired — release the gate
                self._clear_pending_buy(sym)

        # SELL fill confirmation: pos_qty went from >0 → 0
        if sym in self._pending_sell:
            if pos_qty == 0:
                self._pending_sell.pop(sym)
                self._ticks_held.pop(sym, None)
            elif tc - self._pending_sell[sym] >= _MAX_PENDING_TICKS:
                self._pending_sell.pop(sym)

        # ------------------------------------------------------------------
        # 6. Latency guard — block ALL new decisions while order is in-flight
        # ------------------------------------------------------------------
        if sym in self._pending_buy or sym in self._pending_sell:
            return []

        # ------------------------------------------------------------------
        # 7. EXIT logic — only when holding a position
        # ------------------------------------------------------------------
        if pos_qty > 0:
            held = self._ticks_held.get(sym, 0) + 1
            self._ticks_held[sym] = held

            entry_px = float(pos.avg_cost)
            bid0 = float(snap.bid_px[0])

            if entry_px > 0:
                # (1) Profit target — gain measured at current bid (maker fill price)
                gain_bps = (bid0 - entry_px) / entry_px * 1e4
                if gain_bps >= self.profit_target_bps:
                    self._pending_sell[sym] = tc
                    self._ticks_held[sym] = 0
                    return [Order(sym, SELL, pos_qty, MARKET, tag="profit_target")]

                # (2) Stop loss — bid_px[0] mandatory (§2 python_impl_patterns).
                #    5-tick guard absorbs fill-spread gap (strat_0028 anti-pattern).
                if held >= 5:
                    loss_bps = (entry_px - bid0) / entry_px * 1e4
                    if loss_bps >= self.stop_loss_bps:
                        self._pending_sell[sym] = tc
                        self._ticks_held[sym] = 0
                        return [Order(sym, SELL, pos_qty, MARKET, tag="stop_loss")]

            # (3) Time stop — independent of entry_ttl_ticks (Fix 4)
            if held >= self.time_stop_ticks:
                self._pending_sell[sym] = tc
                self._ticks_held[sym] = 0
                return [Order(sym, SELL, pos_qty, MARKET, tag="time_stop")]

            # Still holding — no exit triggered
            return []

        # ------------------------------------------------------------------
        # 8. CANCEL logic — TTL and bid-drop for resting LIMIT BUY
        #    Only relevant when flat (no position) and not pending (guarded above).
        # ------------------------------------------------------------------
        if sym in self._submit_tick:
            tick_size = self._tick_size(sym, fallback=1)
            elapsed = tc - self._submit_tick[sym]
            bid_drop = self._submit_bid[sym] - int(snap.bid_px[0])

            if elapsed >= self.entry_ttl_ticks:
                self._clear_pending_buy(sym)
                return [Order(sym, None, 0, order_type=CANCEL, tag="ttl_cancel")]

            if bid_drop >= self.cancel_on_bid_drop_ticks * tick_size:
                self._clear_pending_buy(sym)
                return [Order(sym, None, 0, order_type=CANCEL, tag="bid_drop_cancel")]

        # ------------------------------------------------------------------
        # 9. ENTRY logic — only when: flat, not pending, sessions/cap allow
        # ------------------------------------------------------------------

        # Fix 2 (pre-order position cap, explicit double-guard):
        # pos_qty > 0 should not be reachable here (exit block above handles it),
        # but _pending_buy could theoretically be re-set by a race — explicit check
        # prevents any future refactor from bypassing the latency guard.
        if pos_qty > 0 or sym in self._pending_buy:
            return []

        # Session entry cap (§7 python_impl_patterns)
        if self._entries_today.get(sym, 0) >= self.max_entries_per_session:
            return []

        # Spread gate (§3 python_impl_patterns):
        #   reject entry if spread_bps >= profit_target_bps — trade would be fee-negative
        if self.spread_gate:
            sp_bps = self._spread_bps(snap)
            if sp_bps >= self.profit_target_bps:
                return []

        # Fix 1 — OBI gate is the FINAL check immediately before Order() construction.
        # No code path can bypass this and reach the submit block below.
        obi_fn = SIGNAL_REGISTRY["obi"]
        obi_1 = obi_fn(snap, st, depth=1)
        sym_threshold = self.obi_thresholds.get(sym, 0.9)
        if obi_1 < sym_threshold:
            return []

        # All gates passed — submit LIMIT BUY at best bid (passive maker, 0-fee)
        limit_px = int(snap.bid_px[0])

        # Book-keeping: set all three tracking dicts atomically before return
        self._pending_buy[sym] = tc
        self._submit_tick[sym] = tc
        self._submit_bid[sym] = limit_px
        self._entries_today[sym] = self._entries_today.get(sym, 0) + 1

        return [Order(sym, BUY, self.lot_size, LIMIT, limit_price=limit_px, tag="entry")]
