"""lob_iter1_obi1_spread_capture — auto-generated by strategy-coder.

Paradigm: spread_capture (LOB-informed directional taker entry).
Signal:   OBI(depth=1) >= symbol-specific 90th-percentile threshold.
Entry:    MARKET BUY when signal fires AND flat AND entries_today < cap.
Exit priority:
  1. time_stop at 10 ticks post-fill (PRIMARY — delivers +0.38 bps terminal EV)
  2. stop_loss 1.78 bps using bid_px[0] (NOT mid — see §2 of python_impl_patterns.md)
  3. profit_target 1.09 bps LIMIT SELL at entry_price * (1 + pt_bps/1e4)
No trailing stop (disabled; too noisy at 100ms cadence).
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

from engine.data_loader import OrderBookSnapshot
from engine.signals import SIGNAL_REGISTRY, SymbolState, update_state
from engine.simulator import BUY, LIMIT, MARKET, SELL, Context, Order

_MAX_PENDING_TICKS = 100  # ticks before assuming rejection; >> 5ms latency at 100ms cadence


@dataclass
class _HoldingState:
    """Per-symbol holding state — created on confirmed BUY fill."""
    entry_tick: int        # tc at which BUY fill was confirmed
    entry_mid: float       # snap.mid when fill was confirmed
    entry_px: float        # pos.avg_cost (avg cost from engine — fill at ask)
    pt_limit_price: int    # LIMIT SELL price for profit target
    pt_submitted: bool     # whether the PT LIMIT SELL is resting
    ticks_held: int        # incremented every tick while holding


class Strategy:
    def __init__(self, spec: dict) -> None:
        p = spec.get("params") or {}

        # --- alpha params ---
        raw_thresholds = p.get("obi_thresholds", {})
        self.obi_thresholds: dict[str, float] = {
            k: float(v) for k, v in raw_thresholds.items()
        }
        # fallback defaults if not present in spec (should always be present)
        self.obi_thresholds.setdefault("BTCUSDT", 0.91469)
        self.obi_thresholds.setdefault("ETHUSDT", 0.942049)
        self.obi_thresholds.setdefault("SOLUSDT", 0.749589)

        # --- execution params ---
        self.profit_target_bps = float(p.get("profit_target_bps", 1.09))
        self.stop_loss_bps = float(p.get("stop_loss_bps", 1.78))
        self.time_stop_ticks = int(p.get("time_stop_ticks", 10))
        self.lot_size = int(p.get("lot_size", 1))
        self.max_entries_per_session = int(p.get("max_entries_per_session", 500))
        self.max_position_per_symbol = int(p.get("max_position_per_symbol", 1))

        # --- signal primitive ---
        self._obi = SIGNAL_REGISTRY["obi"]

        # --- per-symbol signal state ---
        self.states: dict[str, SymbolState] = {}

        # --- per-symbol tick counter ---
        self._tick_count: dict[str, int] = {}

        # --- latency guard: pending order tracking ---
        # sym → tc at which order was submitted
        self._pending_buy: dict[str, int] = {}
        self._pending_sell: dict[str, int] = {}

        # --- per-symbol holding state (populated on confirmed fill) ---
        self._holdings: dict[str, _HoldingState] = {}

        # --- session entry counter ---
        self._entries_today: dict[str, int] = {}
        self._last_date: dict[str, str] = {}

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _state(self, symbol: str) -> SymbolState:
        if symbol not in self.states:
            self.states[symbol] = SymbolState(symbol=symbol)
        return self.states[symbol]

    def _date_str_utc(self, ts_ns: int) -> str:
        """UTC date string from nanosecond timestamp."""
        return datetime.fromtimestamp(ts_ns / 1e9, tz=timezone.utc).strftime("%Y%m%d")

    def _reset_date_if_needed(self, sym: str, ts_ns: int) -> None:
        """Reset daily entry counter when UTC date changes."""
        d = self._date_str_utc(ts_ns)
        if self._last_date.get(sym) != d:
            self._last_date[sym] = d
            self._entries_today[sym] = 0

    def _entries_ok(self, sym: str) -> bool:
        return self._entries_today.get(sym, 0) < self.max_entries_per_session

    # ------------------------------------------------------------------
    # on_tick
    # ------------------------------------------------------------------

    def on_tick(self, snap: OrderBookSnapshot, ctx: Context) -> list[Order]:
        sym = snap.symbol
        st = self._state(sym)
        update_state(st, snap)

        # increment per-symbol tick counter
        tc = self._tick_count.get(sym, 0) + 1
        self._tick_count[sym] = tc

        # reset daily counter on date boundary
        self._reset_date_if_needed(sym, snap.ts_ns)

        # read current position from engine (truth — reflects confirmed fills)
        pos = ctx.portfolio.positions.get(sym)
        pos_qty = pos.qty if pos else 0
        mid = float(snap.mid)

        # ==============================================================
        # LATENCY GUARD — fill confirmation & pending expiry
        # ==============================================================

        # BUY confirmation: pos became non-zero → fill confirmed
        if sym in self._pending_buy:
            if pos_qty > 0:
                # Fill confirmed — init holding state
                del self._pending_buy[sym]
                entry_px = float(pos.avg_cost)
                pt_price = int(entry_px * (1.0 + self.profit_target_bps / 1e4))
                self._holdings[sym] = _HoldingState(
                    entry_tick=tc,
                    entry_mid=mid,
                    entry_px=entry_px,
                    pt_limit_price=pt_price,
                    pt_submitted=False,
                    ticks_held=0,
                )
            elif tc - self._pending_buy[sym] >= _MAX_PENDING_TICKS:
                # Assumed rejected / not filled — reset
                del self._pending_buy[sym]

        # SELL confirmation: pos became zero → exit confirmed
        if sym in self._pending_sell:
            if pos_qty == 0:
                del self._pending_sell[sym]
                self._holdings.pop(sym, None)
            elif tc - self._pending_sell[sym] >= _MAX_PENDING_TICKS:
                # Assumed not filled — retry next tick
                del self._pending_sell[sym]

        # Block all new orders while any order is in flight
        if sym in self._pending_buy or sym in self._pending_sell:
            return []

        # ==============================================================
        # HOLDING PATH — exit logic
        # ==============================================================

        if pos_qty > 0:
            hold = self._holdings.get(sym)
            if hold is None:
                # Engine has a position but we have no holding state.
                # This can happen on strategy restart or forced fills.
                # Reconstruct minimal state from engine position.
                entry_px = float(pos.avg_cost)
                pt_price = int(entry_px * (1.0 + self.profit_target_bps / 1e4))
                hold = _HoldingState(
                    entry_tick=tc,
                    entry_mid=mid,
                    entry_px=entry_px,
                    pt_limit_price=pt_price,
                    pt_submitted=False,
                    ticks_held=0,
                )
                self._holdings[sym] = hold

            hold.ticks_held += 1
            entry_px = float(pos.avg_cost)

            # --- Exit priority 1: time_stop (PRIMARY) ---
            if hold.ticks_held >= self.time_stop_ticks:
                self._pending_sell[sym] = tc
                self._holdings.pop(sym, None)
                return [
                    Order(sym, None, 0, order_type="CANCEL", tag="cancel_pt_on_timestop"),
                    Order(sym, SELL, pos_qty, MARKET, tag="time_stop"),
                ]

            # --- Exit priority 2: stop_loss using bid_px[0] (§2 of python_impl_patterns.md) ---
            # Use bid_px[0] NOT mid — mid is ½ spread above bid, would delay SL trigger
            # 5-tick guard: avoid false trigger from fill-spread gap
            if hold.ticks_held >= 5:
                bid0 = float(snap.bid_px[0])
                loss_bps = (entry_px - bid0) / entry_px * 1e4
                if loss_bps >= self.stop_loss_bps:
                    self._pending_sell[sym] = tc
                    self._holdings.pop(sym, None)
                    return [
                        Order(sym, None, 0, order_type="CANCEL", tag="cancel_pt_on_sl"),
                        Order(sym, SELL, pos_qty, MARKET, tag="stop_loss"),
                    ]

            # --- Exit priority 3: profit_target LIMIT SELL ---
            # Submit once; if not yet resting, submit now.
            if not hold.pt_submitted:
                hold.pt_submitted = True
                return [
                    Order(
                        sym, SELL, pos_qty, LIMIT,
                        limit_price=hold.pt_limit_price,
                        tag="profit_target",
                    )
                ]

            return []

        # ==============================================================
        # FLAT PATH — entry logic
        # ==============================================================

        # Clean up stale holding state if position is flat
        if sym in self._holdings:
            self._holdings.pop(sym, None)

        # max_entries_per_session gate
        if not self._entries_ok(sym):
            return []

        # max_position cap — already holding prevented by pos_qty > 0 above;
        # pending_buy blocked by latency guard above. Both ensure no double fill.

        # OBI(depth=1) signal
        threshold = self.obi_thresholds.get(sym, 1.0)  # default 1.0 = never fire
        obi_1 = self._obi(snap, st, depth=1)
        if obi_1 >= threshold:
            self._pending_buy[sym] = tc
            self._entries_today[sym] = self._entries_today.get(sym, 0) + 1
            return [Order(sym, BUY, self.lot_size, MARKET, tag="obi1_entry")]

        return []
