"""Auto-generated Chain 1 signal module.

spec_id: iter014_wall_break_filter
template: v0.1.0_basic
Generated by chain1.code_generator — DO NOT EDIT by hand.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure chain1.primitives is importable regardless of how this module is loaded.
_REPO_ROOT = Path(__file__).resolve()
for _ in range(6):
    if (_REPO_ROOT / "chain1" / "primitives.py").exists():
        break
    _REPO_ROOT = _REPO_ROOT.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from chain1.primitives import RollingRealizedVol, RollingZScore, ask_depth_concentration, mid_px, trade_imbalance_signed


SPEC_ID = "iter014_wall_break_filter"
THRESHOLD = 5.0
DIRECTION = "long_if_neg"
HORIZON_TICKS = 50

# Stateful helper instances (one per unique helper × primitive × window)
_HELPER_zscore_ask_depth_concentration_300 = RollingZScore(300)
_HELPER_rolling_realized_vol_mid_px_100 = RollingRealizedVol(100)
_HELPER_zscore_trade_imbalance_signed_300 = RollingZScore(300)

def signal(snap) -> float:
    """Compute signal scalar. Decision rule lives in backtest_runner."""
    return _HELPER_zscore_ask_depth_concentration_300.update(ask_depth_concentration(snap)) * (_HELPER_rolling_realized_vol_mid_px_100.update(mid_px(snap)) < 30) * (_HELPER_zscore_trade_imbalance_signed_300.update(trade_imbalance_signed(snap, getattr(snap, 'prev', None))) < 1.0)
