"""Auto-generated Chain 1 signal module.

spec_id: iter014_book_divergence_short_horizon
template: v0.1.0_basic
Generated by chain1.code_generator — DO NOT EDIT by hand.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure chain1.primitives is importable regardless of how this module is loaded.
_REPO_ROOT = Path(__file__).resolve()
for _ in range(6):
    if (_REPO_ROOT / "chain1" / "primitives.py").exists():
        break
    _REPO_ROOT = _REPO_ROOT.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from chain1.primitives import obi_1, obi_ex_bbo


SPEC_ID = "iter014_book_divergence_short_horizon"
THRESHOLD = 1.2
DIRECTION = "long_if_pos"
HORIZON_TICKS = 1



def signal(snap) -> float:
    """Compute signal scalar. Decision rule lives in backtest_runner."""
    return obi_1(snap) - obi_ex_bbo(snap)
