"""Auto-generated Chain 1 signal module.

spec_id: iter001_ofi_proxy_zscore_gt_20
template: v0.1.0_basic
Generated by chain1.code_generator — DO NOT EDIT by hand.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure chain1.primitives is importable regardless of how this module is loaded.
_REPO_ROOT = Path(__file__).resolve()
for _ in range(6):
    if (_REPO_ROOT / "chain1" / "primitives.py").exists():
        break
    _REPO_ROOT = _REPO_ROOT.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from chain1.primitives import RollingZScore, ofi_proxy


SPEC_ID = "iter001_ofi_proxy_zscore_gt_20"
THRESHOLD = 2.0
DIRECTION = "long_if_pos"
HORIZON_TICKS = 1

# Stateful helper instances (one per unique helper × primitive × window)
_HELPER_zscore_ofi_proxy_300 = RollingZScore(300)

def signal(snap) -> float:
    """Compute signal scalar. Decision rule lives in backtest_runner."""
    return _HELPER_zscore_ofi_proxy_300.update(ofi_proxy(snap))
