"""Auto-generated Chain 1 signal module.

spec_id: iter005_ofi_cks_rolling_norm
template: v0.1.0_basic
Generated by chain1.code_generator — DO NOT EDIT by hand.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure chain1.primitives is importable regardless of how this module is loaded.
_REPO_ROOT = Path(__file__).resolve()
for _ in range(6):
    if (_REPO_ROOT / "chain1" / "primitives.py").exists():
        break
    _REPO_ROOT = _REPO_ROOT.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from chain1.primitives import RollingMean, RollingStd, ofi_cks_1


SPEC_ID = "iter005_ofi_cks_rolling_norm"
THRESHOLD = 1.0
DIRECTION = "long_if_pos"
HORIZON_TICKS = 1

# Stateful helper instances (one per unique helper × primitive × window)
_HELPER_rolling_mean_ofi_cks_1_50 = RollingMean(50)
_HELPER_rolling_std_ofi_cks_1_50 = RollingStd(50)

def signal(snap) -> float:
    """Compute signal scalar. Decision rule lives in backtest_runner."""
    return _HELPER_rolling_mean_ofi_cks_1_50.update(ofi_cks_1(snap, getattr(snap, 'prev', None))) / _HELPER_rolling_std_ofi_cks_1_50.update(ofi_cks_1(snap, getattr(snap, 'prev', None)))
