"""Auto-generated Chain 1 signal module.

spec_id: iter007_obi_micro_momentum_trifecta
template: v0.1.0_basic
Generated by chain1.code_generator — DO NOT EDIT by hand.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure chain1.primitives is importable regardless of how this module is loaded.
_REPO_ROOT = Path(__file__).resolve()
for _ in range(6):
    if (_REPO_ROOT / "chain1" / "primitives.py").exists():
        break
    _REPO_ROOT = _REPO_ROOT.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from chain1.primitives import RollingMomentum, microprice_dev_bps, mid_px, obi_1


SPEC_ID = "iter007_obi_micro_momentum_trifecta"
THRESHOLD = 0.5
DIRECTION = "long_if_pos"
HORIZON_TICKS = 1

# Stateful helper instances (one per unique helper × primitive × window)
_HELPER_rolling_momentum_mid_px_50 = RollingMomentum(50)

def signal(snap) -> float:
    """Compute signal scalar. Decision rule lives in backtest_runner."""
    return obi_1(snap) > 0.7 and microprice_dev_bps(snap) > 1.0 and (_HELPER_rolling_momentum_mid_px_50.update(mid_px(snap)) > 0)
