"""lob_run20260420_iter1_obi1_maker — auto-generated by strategy-coder.

LOB spread_capture strategy using OBI depth=1 signal (passive maker).
Entry: LIMIT BUY at bid_px[0] when obi_1 >= symbol-specific threshold
       AND spread_bps < profit_target_bps (spread gate).
Exit: profit_target | stop_loss | time_stop (all via MARKET SELL).
TTL + bid-drop cancel protect resting LIMIT orders from adverse selection.

Patterns applied (from python_impl_patterns.md):
  sl_on_bid_px, per_symbol_spread_gate, latency_guard, entry_ttl,
  bid_drop_cancel, trailing_state_machine (disabled, trailing_stop=False),
  max_entries_per_session, tick_size_estimation
"""
from __future__ import annotations

from collections import deque
from datetime import datetime, timezone

from engine.data_loader import OrderBookSnapshot
from engine.signals import SIGNAL_REGISTRY, SymbolState, update_state
from engine.simulator import BUY, CANCEL, LIMIT, MARKET, SELL, Context, Order

# ---------------------------------------------------------------------------
# Module-level constant
# ---------------------------------------------------------------------------
_MAX_PENDING_TICKS = 100  # staleness timeout — assumed rejected after this many ticks


class Strategy:
    def __init__(self, spec: dict) -> None:
        p = spec.get("params") or {}

        # --- alpha params ---
        raw_thresholds = p.get("obi_thresholds", {})
        self.obi_thresholds: dict[str, float] = {k: float(v) for k, v in raw_thresholds.items()}
        self.spread_gate: bool = bool(p.get("spread_gate", True))

        # --- entry execution params ---
        self.entry_ttl_ticks: int = int(p.get("entry_ttl_ticks", 10))
        self.cancel_on_bid_drop_ticks: int = int(p.get("cancel_on_bid_drop_ticks", 1))

        # --- exit execution params ---
        self.profit_target_bps: float = float(p.get("profit_target_bps", 1.21))
        self.stop_loss_bps: float = float(p.get("stop_loss_bps", 1.64))
        self.trailing_stop: bool = bool(p.get("trailing_stop", False))

        # --- sizing / session ---
        self.lot_size: int = int(p.get("lot_size", 1))
        self.max_entries_per_session: int = int(p.get("max_entries_per_session", 5))
        self.max_position_per_symbol: int = int(p.get("max_position_per_symbol", 1))

        # --- signal states (engine signals) ---
        self.states: dict[str, SymbolState] = {}

        # --- per-symbol tick counter ---
        self._tick_count: dict[str, int] = {}

        # --- latency guard: pending buy/sell ---
        # value = tick when submitted (for _MAX_PENDING_TICKS expiry)
        self._pending_buy: dict[str, int] = {}
        self._pending_sell: dict[str, int] = {}

        # --- TTL and bid-drop cancel ---
        self._submit_tick: dict[str, int] = {}   # sym → tick at BUY LIMIT submit
        self._submit_bid: dict[str, int] = {}    # sym → bid_px[0] at BUY LIMIT submit

        # --- ticks held in position (for time_stop + SL guard) ---
        self._ticks_held: dict[str, int] = {}

        # --- session entry counter ---
        self._entries_today: dict[str, int] = {}
        self._last_date: dict[str, str] = {}

        # --- tick size estimation ---
        self._bid_buf: dict[str, deque] = {}

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _sym_state(self, symbol: str) -> SymbolState:
        if symbol not in self.states:
            self.states[symbol] = SymbolState(symbol=symbol)
        return self.states[symbol]

    def _update_bid_buf(self, snap: OrderBookSnapshot) -> None:
        sym = snap.symbol
        buf = self._bid_buf.setdefault(sym, deque(maxlen=20))
        buf.append(int(snap.bid_px[0]))

    def _tick_size(self, sym: str, fallback: int = 1) -> int:
        """Estimate tick size from recent bid_px[0] diffs (§10 python_impl_patterns)."""
        buf = self._bid_buf.get(sym)
        if not buf or len(buf) < 2:
            return fallback
        diffs = [abs(buf[i] - buf[i - 1]) for i in range(1, len(buf))]
        nonzero = [d for d in diffs if d > 0]
        return min(nonzero) if nonzero else fallback

    def _spread_bps(self, snap: OrderBookSnapshot) -> float:
        """Compute spread_bps manually — no spread_bps property on OrderBookSnapshot (§3)."""
        mid = float(snap.mid)
        if mid <= 0:
            return 0.0
        return float(snap.spread) / mid * 1e4

    def _date_reset(self, snap: OrderBookSnapshot) -> None:
        """Reset per-session counter when UTC date changes (§4 python_impl_patterns)."""
        sym = snap.symbol
        dt = datetime.fromtimestamp(snap.ts_ns / 1e9, tz=timezone.utc)
        date_str = dt.strftime("%Y%m%d")
        if self._last_date.get(sym) != date_str:
            self._last_date[sym] = date_str
            self._entries_today[sym] = 0

    # ------------------------------------------------------------------
    # Main tick handler
    # ------------------------------------------------------------------

    def on_tick(self, snap: OrderBookSnapshot, ctx: Context) -> list[Order]:
        sym = snap.symbol

        # 1. Increment per-symbol tick counter
        tc = self._tick_count.get(sym, 0) + 1
        self._tick_count[sym] = tc

        # 2. Update signal state + bid buffer
        st = self._sym_state(sym)
        update_state(st, snap)
        self._update_bid_buf(snap)

        # 3. Date-change reset (session counter)
        self._date_reset(snap)

        # 4. Current position
        pos = ctx.portfolio.positions.get(sym)
        pos_qty = pos.qty if pos else 0

        # ------------------------------------------------------------------
        # 5. Fill confirmation — check if pending buy/sell resolved
        # ------------------------------------------------------------------
        if sym in self._pending_buy:
            if pos_qty > 0:
                # BUY confirmed — initialise exit tracking
                del self._pending_buy[sym]
                self._pending_buy.pop(sym, None)  # already deleted above (harmless)
                self._ticks_held[sym] = 0
                # clear any stale submit-tracking entries
                self._submit_tick.pop(sym, None)
                self._submit_bid.pop(sym, None)
            elif tc - self._pending_buy[sym] >= _MAX_PENDING_TICKS:
                # Assumed rejected / never filled
                del self._pending_buy[sym]
                self._submit_tick.pop(sym, None)
                self._submit_bid.pop(sym, None)

        if sym in self._pending_sell:
            if pos_qty == 0:
                # SELL confirmed — flat
                del self._pending_sell[sym]
                self._ticks_held.pop(sym, None)
            elif tc - self._pending_sell[sym] >= _MAX_PENDING_TICKS:
                del self._pending_sell[sym]

        # ------------------------------------------------------------------
        # 6. Latency guard — block all decisions while an order is in-flight
        # ------------------------------------------------------------------
        if sym in self._pending_buy or sym in self._pending_sell:
            return []

        # ------------------------------------------------------------------
        # 7. EXIT logic — runs when holding a position
        # ------------------------------------------------------------------
        if pos_qty > 0:
            held = self._ticks_held.get(sym, 0) + 1
            self._ticks_held[sym] = held

            entry_px = float(pos.avg_cost)
            bid0 = float(snap.bid_px[0])

            # --- Profit target (bid_px[0] vs entry; maker fill is at bid) ---
            if entry_px > 0:
                gain_bps = (bid0 - entry_px) / entry_px * 1e4
                if gain_bps >= self.profit_target_bps:
                    self._pending_sell[sym] = tc
                    self._ticks_held[sym] = 0
                    return [Order(sym, SELL, pos_qty, MARKET, tag="profit_target")]

            # --- Stop loss (§2 python_impl_patterns — bid_px[0] mandatory; 5-tick guard) ---
            if entry_px > 0 and held >= 5:
                loss_bps = (entry_px - bid0) / entry_px * 1e4
                if loss_bps >= self.stop_loss_bps:
                    self._pending_sell[sym] = tc
                    self._ticks_held[sym] = 0
                    return [Order(sym, SELL, pos_qty, MARKET, tag="stop_loss")]

            # --- Time stop (entry_ttl_ticks ticks post fill) ---
            if held >= self.entry_ttl_ticks:
                self._pending_sell[sym] = tc
                self._ticks_held[sym] = 0
                return [Order(sym, SELL, pos_qty, MARKET, tag="time_stop")]

            # Still holding — no exit triggered
            return []

        # ------------------------------------------------------------------
        # 8. CANCEL logic — TTL and bid-drop for resting LIMIT BUY
        # ------------------------------------------------------------------
        if sym in self._submit_tick:
            tick_size = self._tick_size(sym, fallback=1)
            elapsed = tc - self._submit_tick[sym]
            bid_drop = self._submit_bid[sym] - int(snap.bid_px[0])

            if elapsed >= self.entry_ttl_ticks:
                del self._submit_tick[sym]
                del self._submit_bid[sym]
                # _pending_buy already cleared in fill-confirmation block above
                # (if we reach here, pending_buy is not set — but clean up anyway)
                self._pending_buy.pop(sym, None)
                return [Order(sym, None, 0, order_type=CANCEL, tag="ttl_cancel")]

            if bid_drop >= self.cancel_on_bid_drop_ticks * tick_size:
                del self._submit_tick[sym]
                del self._submit_bid[sym]
                self._pending_buy.pop(sym, None)
                return [Order(sym, None, 0, order_type=CANCEL, tag="bid_drop_cancel")]

        # ------------------------------------------------------------------
        # 9. ENTRY logic — only when flat and no pending orders
        # ------------------------------------------------------------------

        # Session entry cap (§7 python_impl_patterns)
        if self._entries_today.get(sym, 0) >= self.max_entries_per_session:
            return []

        # Position cap — also blocks if pending (already guarded above)
        if pos_qty >= self.max_position_per_symbol * self.lot_size:
            return []

        # Spread gate (§3 python_impl_patterns) — spec says: reject if spread_bps >= profit_target_bps
        if self.spread_gate:
            sp_bps = self._spread_bps(snap)
            if sp_bps >= self.profit_target_bps:
                return []

        # OBI depth=1 signal
        obi_1 = SIGNAL_REGISTRY["obi"](snap, st, depth=1)
        sym_threshold = self.obi_thresholds.get(sym, 0.9)
        if obi_1 < sym_threshold:
            return []

        # All gates passed — submit LIMIT BUY at best bid (passive maker)
        limit_px = int(snap.bid_px[0])
        orders = [Order(sym, BUY, self.lot_size, LIMIT, limit_price=limit_px, tag="entry")]

        # Book-keeping
        self._pending_buy[sym] = tc
        self._submit_tick[sym] = tc
        self._submit_bid[sym] = limit_px
        self._entries_today[sym] = self._entries_today.get(sym, 0) + 1

        return orders
