"""Dummy signal module for Phase B plumbing check.

Handcrafted (not generated by code-generator) — plain `signal()` returning obi_1.
Used to verify the backtest runner works end-to-end before the LLM agents exist.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Make chain1.primitives importable when loaded by backtest_runner
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from chain1.primitives import obi_1  # noqa: E402


SPEC_ID = "iter_dummy_obi_1"
THRESHOLD = 0.2
DIRECTION = "long_if_pos"
HORIZON_TICKS = 1


def signal(snap) -> float:
    """Return obi_1 as the raw signal value."""
    return obi_1(snap)
