"""Auto-generated Chain 1 signal module.

spec_id: iter009_absorption_high_vol
template: v0.1.0_basic
Generated by chain1.code_generator — DO NOT EDIT by hand.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure chain1.primitives is importable regardless of how this module is loaded.
_REPO_ROOT = Path(__file__).resolve()
for _ in range(6):
    if (_REPO_ROOT / "chain1" / "primitives.py").exists():
        break
    _REPO_ROOT = _REPO_ROOT.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from chain1.primitives import RollingRealizedVol, RollingZScore, mid_px, obi_1, trade_imbalance_signed


SPEC_ID = "iter009_absorption_high_vol"
THRESHOLD = 0.5
DIRECTION = "long_if_pos"
HORIZON_TICKS = 10

# Stateful helper instances (one per unique helper × primitive × window)
_HELPER_zscore_trade_imbalance_signed_300 = RollingZScore(300)
_HELPER_rolling_realized_vol_mid_px_100 = RollingRealizedVol(100)

def signal(snap) -> float:
    """Compute signal scalar. Decision rule lives in backtest_runner."""
    return (obi_1(snap) > 0.95 and _HELPER_zscore_trade_imbalance_signed_300.update(trade_imbalance_signed(snap, getattr(snap, 'prev', None))) < -3.0) and _HELPER_rolling_realized_vol_mid_px_100.update(mid_px(snap)) > 40
