"""Auto-generated Chain 1 signal module.

spec_id: iter021_bbo_divergence_low_vol
template: v0.1.0_basic
Generated by chain1.code_generator — DO NOT EDIT by hand.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure chain1.primitives is importable regardless of how this module is loaded.
_REPO_ROOT = Path(__file__).resolve()
for _ in range(6):
    if (_REPO_ROOT / "chain1" / "primitives.py").exists():
        break
    _REPO_ROOT = _REPO_ROOT.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from chain1.primitives import RollingRealizedVol, mid_px, obi_1, obi_ex_bbo


SPEC_ID = "iter021_bbo_divergence_low_vol"
THRESHOLD = 1.2
DIRECTION = "long_if_pos"
HORIZON_TICKS = 1

# Stateful helper instances (one per unique helper × primitive × window)
_HELPER_rolling_realized_vol_mid_px_100 = RollingRealizedVol(100)

def signal(snap) -> float:
    """Compute signal scalar. Decision rule lives in backtest_runner."""
    return (obi_1(snap) - obi_ex_bbo(snap)) * (_HELPER_rolling_realized_vol_mid_px_100.update(mid_px(snap)) < 30)
